export const HARDCODED_QUESTIONS = {
  NAPLAN: [
    // 📖 Reading (3)
    {
      question_id: "naplan_r1",
      question_name:
        "In the sentence 'The boy sprinted across the field', what does 'sprinted' mean?",
      question_options: ["Walked slowly", "Ran quickly", "Jumped high", "Sat down"],
      correct_answer: "Ran quickly",
      explanation: "'Sprinted' means to run very fast.",
      question_category: "reading",
      difficulty_level: "Easy",
      stage_number: 1,
      course_type: "Naplan",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
    {
      question_id: "naplan_r2",
      question_name:
        "A passage describes a forest after a fire. What is the most likely mood?",
      question_options: ["Joyful", "Sad", "Peaceful", "Excited"],
      correct_answer: "Sad",
      explanation: "A burned forest suggests a sad or somber mood.",
      question_category: "reading",
      difficulty_level: "Medium",
      stage_number: 1,
      course_type: "Naplan",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
    {
      question_id: "naplan_r3",
      question_name:
        "What is the main purpose of a newspaper editorial?",
      question_options: [
        "To inform about the weather",
        "To express an opinion",
        "To list movie times",
        "To advertise products",
      ],
      correct_answer: "To express an opinion",
      explanation: "Editorials present opinions and arguments on current issues.",
      question_category: "reading",
      difficulty_level: "Medium",
      stage_number: 1,
      course_type: "Naplan",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },

    // ✍️ Writing (3)
    {
      question_id: "naplan_w1",
      question_name: "Choose the sentence that uses correct punctuation.",
      question_options: [
        "My friend said lets go.",
        "My friend said, lets go.",
        "My friend said, “Let’s go.”",
        "My friend said “lets go”.",
      ],
      correct_answer: "My friend said, “Let’s go.”",
      explanation: "Correct quotation marks and apostrophe usage.",
      question_category: "writing",
      difficulty_level: "Medium",
      stage_number: 1,
      course_type: "Naplan",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
    {
      question_id: "naplan_w2",
      question_name:
        "Which sentence is the best topic sentence for a paragraph about recycling?",
      question_options: [
        "Many people throw away bottles.",
        "Recycling helps reduce waste and protect the environment.",
        "Trash can smell bad in summer.",
        "We use bins every day.",
      ],
      correct_answer: "Recycling helps reduce waste and protect the environment.",
      explanation: "It clearly introduces the main idea of recycling benefits.",
      question_category: "writing",
      difficulty_level: "Medium",
      stage_number: 1,
      course_type: "Naplan",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
    {
      question_id: "naplan_w3",
      question_name:
        "Which word correctly completes the sentence: 'She ______ a letter to her friend.'",
      question_options: ["write", "wrote", "written", "writing"],
      correct_answer: "wrote",
      explanation: "Past tense of 'write' is 'wrote'.",
      question_category: "writing",
      difficulty_level: "Easy",
      stage_number: 1,
      course_type: "Naplan",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },

    // 🔢 Numeracy (2)
    {
      question_id: "naplan_n1",
      question_name: "What is 15 ÷ 3?",
      question_options: ["3", "4", "5", "6"],
      correct_answer: "5",
      explanation: "15 divided by 3 equals 5.",
      question_category: "numeracy",
      difficulty_level: "Easy",
      stage_number: 1,
      course_type: "Naplan",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
    {
      question_id: "naplan_n2",
      question_name:
        "A square has a side length of 6 cm. What is its perimeter?",
      question_options: ["12 cm", "24 cm", "18 cm", "30 cm"],
      correct_answer: "24 cm",
      explanation: "Perimeter = 4 × side = 4 × 6 = 24 cm.",
      question_category: "numeracy",
      difficulty_level: "Easy",
      stage_number: 1,
      course_type: "Naplan",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },

    // 🔤 Language Conventions (2)
    {
      question_id: "naplan_lc1",
      question_name: "Choose the correctly spelled word.",
      question_options: ["definately", "definitely", "definetly", "definetely"],
      correct_answer: "definitely",
      explanation: "‘Definitely’ is the correct spelling.",
      question_category: "language_conventions",
      difficulty_level: "Medium",
      stage_number: 1,
      course_type: "Naplan",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
    {
      question_id: "naplan_lc2",
      question_name:
        "Select the sentence with the correct grammar.",
      question_options: [
        "She don’t like apples.",
        "She doesn’t like apples.",
        "She not like apples.",
        "She don likes apples.",
      ],
      correct_answer: "She doesn’t like apples.",
      explanation: "‘Doesn’t’ agrees with singular subject ‘She’.",
      question_category: "language_conventions",
      difficulty_level: "Easy",
      stage_number: 1,
      course_type: "Naplan",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
  ],

  ISAC: [
    // ➕ Mathematics (2)
    {
      question_id: "isac_m1",
      question_name: "Simplify: 5x + 2x - 4",
      question_options: ["3x - 4", "7x - 4", "x - 4", "9x"],
      correct_answer: "7x - 4",
      explanation: "Combine like terms 5x + 2x = 7x.",
      question_category: "mathematics",
      difficulty_level: "Easy",
      stage_number: 1,
      course_type: "ISAC",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
    {
      question_id: "isac_m2",
      question_name:
        "If the area of a rectangle is 36 cm² and its length is 9 cm, what is its width?",
      question_options: ["3 cm", "4 cm", "6 cm", "8 cm"],
      correct_answer: "4 cm",
      explanation: "Width = Area ÷ Length = 36 ÷ 9 = 4 cm.",
      question_category: "mathematics",
      difficulty_level: "Easy",
      stage_number: 1,
      course_type: "ISAC",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },

    // 📚 Reading Comprehension (3)
    {
      question_id: "isac_rc1",
      question_name:
        "In a story, if the character 'gripped the chair tightly and stared at the floor', how is the character feeling?",
      question_options: ["Calm", "Nervous", "Happy", "Excited"],
      correct_answer: "Nervous",
      explanation: "Body language suggests anxiety.",
      question_category: "reading_comprehension",
      difficulty_level: "Medium",
      stage_number: 1,
      course_type: "ISAC",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
    {
      question_id: "isac_rc2",
      question_name:
        "What is the main purpose of an instructional text?",
      question_options: [
        "To entertain",
        "To inform how to do something",
        "To describe feelings",
        "To tell a story",
      ],
      correct_answer: "To inform how to do something",
      explanation: "Instructional texts guide the reader through steps.",
      question_category: "reading_comprehension",
      difficulty_level: "Easy",
      stage_number: 1,
      course_type: "ISAC",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
    {
      question_id: "isac_rc3",
      question_name:
        "If a passage ends with 'And that day, she learned to forgive', what theme is shown?",
      question_options: [
        "Anger",
        "Revenge",
        "Forgiveness",
        "Adventure",
      ],
      correct_answer: "Forgiveness",
      explanation: "The lesson of the passage centers on forgiving others.",
      question_category: "reading_comprehension",
      difficulty_level: "Medium",
      stage_number: 1,
      course_type: "ISAC",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },

    // ✍️ Writing (3)
    {
      question_id: "isac_w1",
      question_name:
        "Which sentence uses correct punctuation?",
      question_options: [
        "Although it was raining we went outside.",
        "Although it was raining, we went outside.",
        "Although it was raining we, went outside.",
        "Although, it was raining we went outside.",
      ],
      correct_answer: "Although it was raining, we went outside.",
      explanation: "A comma separates the dependent and main clause.",
      question_category: "writing",
      difficulty_level: "Medium",
      stage_number: 1,
      course_type: "ISAC",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
    {
      question_id: "isac_w2",
      question_name:
        "Choose the best concluding sentence for a story about teamwork.",
      question_options: [
        "We all went home.",
        "Working together helped us win the game.",
        "It was a long day.",
        "Everyone was tired after the match.",
      ],
      correct_answer: "Working together helped us win the game.",
      explanation: "It summarizes the theme of teamwork.",
      question_category: "writing",
      difficulty_level: "Easy",
      stage_number: 1,
      course_type: "ISAC",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
    {
      question_id: "isac_w3",
      question_name:
        "Which word completes the sentence correctly? 'The students ______ waiting for the results.'",
      question_options: ["is", "are", "was", "be"],
      correct_answer: "are",
      explanation: "Plural subject 'students' takes 'are'.",
      question_category: "writing",
      difficulty_level: "Easy",
      stage_number: 1,
      course_type: "ISAC",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },

    // 💭 Critical Thinking (2)
    {
      question_id: "isac_ct1",
      question_name:
        "All cats are animals. Some animals are not cats. Which statement is true?",
      question_options: [
        "All animals are cats.",
        "Some animals are not cats.",
        "No animals are cats.",
        "All animals are cats or dogs.",
      ],
      correct_answer: "Some animals are not cats.",
      explanation: "The statement follows directly from the premise.",
      question_category: "critical_thinking",
      difficulty_level: "Medium",
      stage_number: 1,
      course_type: "ISAC",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
    {
      question_id: "isac_ct2",
      question_name:
        "You notice plants near the window grow faster than those in the dark corner. What can you infer?",
      question_options: [
        "Plants grow faster without sunlight.",
        "Plants need sunlight to grow well.",
        "Plants prefer dark areas.",
        "Plants don’t need light.",
      ],
      correct_answer: "Plants need sunlight to grow well.",
      explanation: "Sunlight promotes photosynthesis, enabling growth.",
      question_category: "critical_thinking",
      difficulty_level: "Easy",
      stage_number: 1,
      course_type: "ISAC",
      time_spent: 0,
      user_answer: null,
      is_correct: false,
      question_attempted: false,
    },
  ],
};
